### ISSUE TITLE
iOS 13 issue

### ISSUE THREAD

**Issue by jaycop85** [serratus/quaggaJS#378]
It seems like there is an issue with iOS 13 (developer beta 3).
I tried to open the live preview example (https://serratus.github.io/quaggaJS/examples/live_w_locator.html) but the camera feed won't start. I can also no longer select the camera device (front or back camera).

**Comment by jaycop85** [comment]
i tested on an iPhone 7, iOS 13 developer beta 3, safari

**Comment by Agasd** [comment]
Same issue, I6S probably an issue with safari and the getUserMedia because I can't use other sites either to access the camera. I hope it'll get fixed soon

**Comment by jaycop85** [comment]
Issue has been fixed apparently, with developer beta 5

**Comment by nathanchase** [comment]
It has not been fixed. Just updated to beta 5 last night (7/30/19) and it's still broken.

**Comment by ericblade** [comment]
It seems that developer previews of iOS frequently shut off the camera permissions in Safari.  Might want to check your camera permissions in Settings whenever you install a dev beta.
